# Generated by Django 5.1.3 on 2024-12-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='corretores/')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], max_length=15)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='Models.corretor')),
            ],
        ),
    ]
